START TRANSACTION;

DROP TABLE IF EXISTS ProductData;

CREATE TABLE ProductData (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  image BLOB,
  description MEDIUMTEXT
);

CREATE TABLE ProductDataSequence (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) AUTO_INCREMENT = 1;
INSERT INTO ProductDataSequence VALUES (0);

COMMIT;